apiVersion: v1
kind: Service
metadata:
  name: {{ include "av-scan-service.fullname" . }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "av-scan-service.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.tls.generateCerts.enabled ( eq .Values.tls.generateCerts.executor "openshift" ) }}
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.tls.secretName }} # for openshift 3.X
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.tls.secretName }}  # for openshift 4.X
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.tls.enabled }}
    - targetPort: https
      protocol: TCP
      name: https
      port: 443
    {{- else }}
    - targetPort: http
      protocol: TCP
      name: http
      port: 80
    {{- end }}
  selector:
    {{- include "av-scan-service.selectorLabels" . | nindent 4 }}
