{{- if and .Values.tls.generateCerts.enabled ( eq .Values.tls.generateCerts.executor "cert-manager" ) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: av-scan-service-tls-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "av-scan-service.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  duration: {{ default 365 .Values.tls.generateCerts.duration | mul 24 }}h
  commonName: av-scan-service-ca
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "av-scan-service.certDnsNames" . | indent 4) }}
  ipAddresses:
{{ ( include "av-scan-service.certIpAddresses" . | indent 4) }}
  issuerRef:
    {{- if .Values.tls.generateCerts.clusterIssuerName }}
    name: {{ .Values.tls.generateCerts.clusterIssuerName }}
    kind: ClusterIssuer
    {{- else }}
    name: av-scan-service-tls-issuer
    kind: Issuer
    {{- end }}
    group: cert-manager.io
{{- end }}
