{{- if and ( and .Values.tls.generateCerts.enabled ( eq .Values.tls.generateCerts.executor "cert-manager" ) ) (not .Values.tls.generateCerts.clusterIssuerName) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: av-scan-service-tls-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "av-scan-service.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
