{{ if and .Values.tls.crt .Values.tls.key }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "av-scan-service.labels" . | nindent 4 }}
data:
  ca.crt: "{{ .Values.tls.ca | b64enc }}"
  tls.crt: "{{ .Values.tls.crt | b64enc }}"
  tls.key: "{{ .Values.tls.key | b64enc }}"
type: kubernetes.io/tls
{{ end }}
