apiVersion: v2
name: av-scan-service
description: A Helm chart for Kubernetes and OpenShift
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
# It will be replaced automatically with release version during the 'Helm Charts Release' workflow
version: 0.10.4
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# For av-scan-service, it is the same as the ClamAV version.
appVersion: "1.5.1-11"