{
 "title": "Antivirus Service",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [ "av-scan-service" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(av_viruses_found_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(av_viruses_found_total{cluster=\"$cluster\", job!=\"kube-apiserver\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(av_viruses_found_total{cluster=\"$cluster\", namespace=\"$namespace\", job!=\"kube-apiserver\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Viruses Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Viruses Found Total",
   "type": "timeseries",
   "description": "Shows total number of found viruses across all pods in the given namespace",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(delta(av_viruses_found_total{cluster=~\"$cluster\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "Found Viruses"
    }
   ]
  },
  {
   "title": "Viruses Database Age Max",
   "type": "stat",
   "description": "Shows maximum viruses database age across all pods in the given namespace",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(av_database_age_seconds{cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP request by code: 2xx or 3xx $pod",
   "type": "timeseries",
   "description": "Shows amount of successful requests to different endpoints per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{cluster=~\"$cluster\", namespace=\"$namespace\", code=~\"2..|3..\", pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}, status={{ code }}"
    }
   ]
  },
  {
   "title": "HTTP inflight requests $pod",
   "type": "timeseries",
   "description": "Shows amount of in-progress requests to different endpoints",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "http_requests_inflight{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "HTTP 95%-tile latency of response time $pod",
   "type": "timeseries",
   "description": "How long it took to process a request, partitioned by endpoint and status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(http_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval])) by (handler,code,le)\r\n)",
     "legendFormat": "{{ handler }}, status={{ code }}"
    }
   ]
  },
  {
   "title": "HTTP average request size $pod",
   "type": "timeseries",
   "description": "Shows average request size to different endpoints",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]) / rate(http_request_size_bytes_count{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}, status={{ code }}"
    }
   ]
  },
  { "title": "HTTP Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP requests by code: 4xx $pod",
   "type": "timeseries",
   "description": "Shows amount of requests to different endpoints per second with code 4xx",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", code=~\"4..\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "HTTP requests by code: 5xx $pod",
   "type": "timeseries",
   "description": "Shows amount of requests to different endpoints per second with code 5xx",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", code=~\"5..\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}